source_dir(PATH_TRAIN_MODELS, local = shared_env)
source_dir(PATH_IMPORT_DATA, local = shared_env, recursive = TRUE)
source_dir(PATH_EXP_IMPORT, local = shared_env, recursive = TRUE)
source_dir(PATH_EXP_RESULTS, local = shared_env)
source_dir(PATH_SAVE_MODELS, local = shared_env)
